# Generated by Django 3.2.18 on 2023-04-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='uploads',
            field=models.ImageField(blank=True, max_length=4, upload_to='uploads/'),
        ),
    ]
