# Generated by Django 3.2.18 on 2023-04-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_alter_tweet_uploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='uploads',
        ),
        migrations.AddField(
            model_name='tweet',
            name='uploads1',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='uploads2',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='uploads3',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='uploads4',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
