# Generated by Django 3.2.18 on 2023-04-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_auto_20230404_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='uploads1',
            new_name='upload1',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='uploads2',
            new_name='upload2',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='uploads3',
            new_name='upload3',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='uploads4',
            new_name='upload4',
        ),
    ]
