# Generated by Django 3.2.18 on 2023-04-04 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_auto_20230404_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retweet',
            name='retweet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to='tweet.tweet'),
        ),
    ]
