# Generated by Django 3.2.18 on 2023-04-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='likes_choices',
            new_name='like_choices',
        ),
    ]
