# Generated by Django 3.2.18 on 2023-04-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_rename_likes_choices_likes_like_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='likes',
            new_name='tweet',
        ),
    ]
